import type {ListableTask} from './types'

const now = new Date()
const fiveDaysFromNow = new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000)
const twoDaysFromNow = new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000)
const oneDayAgo = new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000)
const sevenDaysFromNow = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000)
const oneDayFromNow = new Date(now.getTime() + 1 * 24 * 60 * 60 * 1000)

export const MOCK_TASKS: ListableTask[] = [
  {
    id: 'task-1',
    title: 'Install HVAC system in unit 2B',
    status: 'InProgress',
    taskType: 'Todo',
    priority: 'Normal',
    dueDate: fiveDaysFromNow.toISOString().split('T')[0],
    startedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    endedAt: Date.now() + 3 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 1 * 60 * 60 * 1000,
    photoCount: 0,
    featuredPhotoUrl: null,
    tags: [
      {id: 'tag-1', name: 'Mechanical', backgroundColor: '#3b82f6'},
      {id: 'tag-2', name: 'Priority', backgroundColor: '#f59e0b'},
    ],
    updatesCount: 3,
    lastCommentCreatedAt: Date.now() - 2 * 60 * 60 * 1000,
    coordinatorId: 'user-1',
    coordinatorName: 'Sarah Johnson',
    coordinatorInitials: 'SJ',
    assignedToId: 'user-2',
    assignedToName: 'Mike Chen',
    assignedToInitials: 'MC',
    projectId: 'proj-1',
    projectName: 'Riverside Apartments',
    workOrderId: 'wo-1',
    workOrderNumber: 'WO-2024-001',
    areaName: 'Mechanical',
    number: 'T-123',
  },
  {
    id: 'task-2',
    title: 'Fix drywall damage in hallway',
    status: 'Open',
    taskType: 'PunchItem',
    priority: 'Urgent',
    dueDate: twoDaysFromNow.toISOString().split('T')[0],
    startedAt: null,
    endedAt: null,
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 30 * 60 * 1000,
    photoCount: 0,
    featuredPhotoUrl: null,
    tags: [{id: 'tag-3', name: 'Urgent', backgroundColor: '#ef4444'}],
    updatesCount: 0,
    lastCommentCreatedAt: null,
    coordinatorId: null,
    coordinatorName: null,
    coordinatorInitials: null,
    assignedToId: null,
    assignedToName: null,
    assignedToInitials: null,
    projectId: 'proj-1',
    projectName: 'Riverside Apartments',
    workOrderId: null,
    workOrderNumber: null,
    areaName: 'Interior',
    number: 'P-456',
  },
  {
    id: 'task-3',
    title: 'Inspect electrical panel',
    status: 'Completed',
    taskType: 'ScheduledTask',
    priority: 'Normal',
    dueDate: oneDayAgo.toISOString().split('T')[0],
    startedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    endedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    photoCount: 0,
    featuredPhotoUrl: null,
    tags: [{id: 'tag-4', name: 'Electrical', backgroundColor: '#8b5cf6'}],
    updatesCount: 5,
    lastCommentCreatedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    coordinatorId: 'user-3',
    coordinatorName: 'Alex Rivera',
    coordinatorInitials: 'AR',
    assignedToId: 'user-4',
    assignedToName: 'Jordan Lee',
    assignedToInitials: 'JL',
    projectId: 'proj-2',
    projectName: 'Downtown Office Complex',
    workOrderId: null,
    workOrderNumber: null,
    areaName: 'Electrical',
    number: 'T-789',
  },
  {
    id: 'task-4',
    title: 'Paint exterior trim',
    status: 'Open',
    taskType: 'Todo',
    priority: 'Normal',
    dueDate: sevenDaysFromNow.toISOString().split('T')[0],
    startedAt: null,
    endedAt: null,
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 10 * 60 * 1000,
    photoCount: 0,
    featuredPhotoUrl: null,
    tags: [],
    updatesCount: 1,
    lastCommentCreatedAt: Date.now() - 5 * 60 * 60 * 1000,
    coordinatorId: 'user-1',
    coordinatorName: 'Sarah Johnson',
    coordinatorInitials: 'SJ',
    assignedToId: null,
    assignedToName: null,
    assignedToInitials: null,
    projectId: 'proj-1',
    projectName: 'Riverside Apartments',
    workOrderId: null,
    workOrderNumber: null,
    areaName: 'Exterior',
    number: 'T-790',
  },
  {
    id: 'task-5',
    title: 'Replace broken window in unit 4C',
    status: 'InReview',
    taskType: 'PunchItem',
    priority: 'Urgent',
    dueDate: oneDayFromNow.toISOString().split('T')[0],
    startedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    endedAt: Date.now() + 1 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 3 * 60 * 60 * 1000,
    photoCount: 0,
    featuredPhotoUrl: null,
    tags: [
      {id: 'tag-3', name: 'Urgent', backgroundColor: '#ef4444'},
      {id: 'tag-5', name: 'Safety', backgroundColor: '#dc2626'},
    ],
    updatesCount: 2,
    lastCommentCreatedAt: Date.now() - 1 * 60 * 60 * 1000,
    coordinatorId: 'user-3',
    coordinatorName: 'Alex Rivera',
    coordinatorInitials: 'AR',
    assignedToId: 'user-2',
    assignedToName: 'Mike Chen',
    assignedToInitials: 'MC',
    projectId: 'proj-1',
    projectName: 'Riverside Apartments',
    workOrderId: 'wo-2',
    workOrderNumber: 'WO-2024-002',
    areaName: 'Exterior',
    number: 'P-457',
  },
]
